repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: check-added-large-files # Prevent giant files from being committed
  - id: check-byte-order-marker # Prevents weird UTF-8 encoding edge cases
  - id: check-case-conflict     # Check if case-insensitive filesystems would bork
  - id: check-docstring-first   # Check for if docstring was misplaced
  - id: check-executables-have-shebangs
  - id: check-json              # Checks for valid json
  - id: check-merge-conflict    # Checks strings that look like a committed merge conflict
  - id: check-xml               # Checks for valid xml
  - id: check-yaml              # Checks for valid yaml
  - id: end-of-file-fixer       # Checks for ending with a newline
  - id: mixed-line-ending       # Consistent LF or CRLF
  - id: trailing-whitespace     # No trailing whitespace
- repo: local
  hooks:
  - id: gdlint
    name: gdlint
    entry: gdlint scripts/
    language: system
    files: ^scripts/.*\.gd$
