
name: Download artifact
description: Download artifact.
inputs:
  name:
    description: The artifact name.
    default: "${{ github.job }}"
  path:
    description: The path to download.
    required: true
    default: "dist/*"
runs:
  using: "composite"
  steps:
    - name: Download Artifact
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.name }}
        path: ${{ inputs.path }}
