---
name: marble
base: core20
version: '1.3'
summary: A marble race minigame
description: |
  A marble race minigame, made with Godot Engine.
grade: devel
confinement: devmode

apps:
  marble:
    command: usr/share/marble/Marble.x86_64 --main-pack $SNAP/usr/share/marble/Marble.pck -S $SNAP_USER_COMMON/save
    plugs:
      - home
      - pulseaudio
      - opengl
      - screen-inhibit-control
      - browser-support
      - x11
    # desktop: /usr/share/applications/org.mechanicalflower.Marble.desktop
    environment:
      LIBGL_DRIVERS_PATH: $SNAP/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/dri

parts:
  marble:
    source: .
    override-build: |
      # Icon paths in the desktop file will be rewritten to use ${SNAP}/<file> if specified as desktop file in snapcraft.yaml
      sed -i.bak -e "s|Icon=org.mechanicalflower.Marble$|Icon=meta/gui/icon.png|g" ${SNAPCRAFT_PART_SRC}/.github/org.mechanicalflower.Marble.desktop
      snapcraftctl build
      mkdir -p ${SNAPCRAFT_PART_INSTALL}/usr/share/marble/
      cp ${SNAPCRAFT_PART_SRC}/Marble.x86_64 ${SNAPCRAFT_PART_INSTALL}/usr/share/marble/Marble.x86_64
      cp ${SNAPCRAFT_PART_SRC}/Marble.pck ${SNAPCRAFT_PART_INSTALL}/usr/share/marble/Marble.pck
    plugin: nil
    override-prime: |
      snapcraftctl prime
      mkdir -p ${SNAPCRAFT_PRIME}/meta/gui
      # cp ${SNAPCRAFT_PART_SRC}/org.mechanicalflower.Marble-256.png ${SNAPCRAFT_PRIME}/meta/gui/icon.png
    stage-packages:
      - libgl1
      - libglvnd0
      - libglx0
      - libx11-6
      - libxau6
      - libxcb1
      - libxcursor1
      - libxdmcp6
      - libxext6
      - libxfixes3
      - libxi6
      - libxinerama1
      - libxrandr2
      - libxrender1
      - libasound2
      - libpulse0
