
---
name: marble-race
base: core20
version: '1.4.3'
summary: A marble race minigame
description: |
  A marble race minigame, made with Godot Engine.
grade: devel
confinement: devmode
license: MIT
architectures: [amd64]

apps:
  marble:
    command: Marble.x86_64 --main-pack $SNAP/Marble.pck --rendering-driver opengl3
    extensions: [gnome-3-38]
    plugs:
      - pulseaudio
      - opengl
      - x11
    desktop: org.mechanicalflower.Marble.desktop
    environment:
      LD_LIBRARY_PATH: "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio:$SNAP"

parts:
  marble-source:
    source: https://github.com/MechanicalFlower/Marble/archive/refs/tags/1.4.3.tar.gz
    override-build: |
      snapcraftctl build

      # Icon paths in the desktop file will be rewritten to use ${SNAP}/<file> if specified as desktop file in snapcraft.yaml
      sed -i.bak -e "s|Icon=org.mechanicalflower.Marble$|Icon=gui/icon.png|g" ${SNAPCRAFT_PART_SRC}/public/packaging/org.mechanicalflower.Marble.desktop

      cp ${SNAPCRAFT_PART_SRC}/public/packaging/org.mechanicalflower.Marble.desktop ${SNAPCRAFT_PART_INSTALL}/org.mechanicalflower.Marble.desktop
    plugin: nil
    override-prime: |
      snapcraftctl prime

      mkdir -p ${SNAPCRAFT_PRIME}/gui
      cp ${SNAPCRAFT_PART_SRC}/assets/icon.png ${SNAPCRAFT_PRIME}/gui/icon.png
  marble-dist:
    source: https://github.com/MechanicalFlower/Marble/releases/download/1.4.3/Marble-linux-v1.4.3.zip
    override-build: |
      snapcraftctl build

      cp ${SNAPCRAFT_PART_SRC}/Marble.x86_64 ${SNAPCRAFT_PART_INSTALL}/Marble.x86_64
      cp ${SNAPCRAFT_PART_SRC}/Marble.pck ${SNAPCRAFT_PART_INSTALL}/Marble.pck

      chmod +x ${SNAPCRAFT_PART_INSTALL}/Marble.x86_64
    plugin: nil
