name: Export Godot game
description: Export Godot game.
inputs:
  name:
    description: The game name.
    required: true
  platform:
    description: The game platform.
    required: true
    type: choice
    options:
    - windows
    - linux
    - mac
    - web
  output:
    description: The game output.
    required: true
  version:
    description: The game version.
    required: true
  godot_version:
    description: The Godot version.
    required: true
  preset:
    description: The export preset.
    required: true
runs:
  using: "composite"
  steps:
    - name: Add Build Info
      uses: robpc/godot-build-info-action@v1
      with:
        version: ${{ inputs.version }}

    - name: Setup Godot
      uses: chickensoft-games/setup-godot@v1
      with:
        version: ${{ inputs.godot_version }}
        use-dotnet: false

    - name: Install Addons
      shell: bash
      run: |
        [ -f plug.gd ] && godot --headless -s plug.gd install || true

    # workaround: https://github.com/godotengine/godot/pull/68461
    - name: Import Assets
      shell: bash
      run: |
        timeout 60 godot --editor --headless || true

    - name: Build ${{ inputs.preset }}
      shell: bash
      run: |
        [ -d build ] && rm -r build
        mkdir -v -p build/${{ inputs.platform }}
        declare -A outputs=(["windows"]="${{ inputs.name }}.exe" ["linux"]="${{ inputs.name }}.x86_64" ["mac"]="${{ inputs.name }}.zip" ["web"]="index.html")
        timeout 60 godot --export-release "${{ inputs.preset }}" --headless ./build/${{ inputs.platform }}/${outputs[${{ inputs.platform }}]} || true
