app: Marble

ingredients:
  dist: trusty
  sources:
    - deb http://us.archive.ubuntu.com/ubuntu/ trusty main universe
  packages:
    - libx11-6
    - libxinerama1
    - libxcursor1
    - libxrandr2
    - libfreetype6
    - libpng12-0
    - libasound2
    - libpulse0
    - libgl1-mesa-glx
    - zlib1g
    - libgcc1
    - libc6
  script:
    # Download released builds
    - wget -c "https://github.com/MechanicalFlower/Marble/releases/download/1.6.0/Marble-linux-v1.6.0.zip"
    - unzip *.zip
    # Download the icon and the .desktop file
    - wget -c "https://raw.githubusercontent.com/MechanicalFlower/Marble/1.6.0/public/packaging/org.mechanicalflower.Marble.desktop"
    - wget -c "https://raw.githubusercontent.com/MechanicalFlower/Marble/1.6.0/assets/icon.png"

script:
  - sed -i.bak -e "s,Version=.*$,,g" ../org.mechanicalflower.Marble.desktop
  # Replace the icon path in the desktop file
  - sed -i.bak -e "s,Icon=org.mechanicalflower.Marble$,Icon=/usr/share/icons/hicolor/apps/marble.png,g" ../org.mechanicalflower.Marble.desktop
  # Replace the exec command in the desktop file
  - sed -i.bak -e "s,Exec=marble-wrapper$,Exec=bin/Marble.x86_64 --main-pack bin/Marble.pck --rendering-driver opengl3,g" ../org.mechanicalflower.Marble.desktop
  # Copy the desktop file
  - mkdir -p usr/share/applications/
  - cp ../org.mechanicalflower.Marble.desktop .
  - cp ../org.mechanicalflower.Marble.desktop usr/share/applications/org.mechanicalflower.Marble.desktop
  # Copy the icon
  - mkdir -p usr/share/icons/hicolor/apps/
  - cp ../icon.png usr/share/icons/hicolor/apps/marble.png
  # Copy game files
  - mkdir -p usr/bin/
  - cp ../Marble.x86_64 usr/bin/Marble.x86_64
  - cp ../Marble.pck usr/bin/Marble.pck
  # Ensure the game is an executable
  - chmod +x usr/bin/Marble.x86_64
