name: Build

on:
  push:
    branches: [main]
    tags: ['*']
  workflow_dispatch:

jobs:
  pre_check:
    runs-on: ubuntu-22.04

    name: Pre-check
    steps:
      - name: Ensure version is bump for tag
        run: |
          game_version=$(cat .version)
          if [[ "${{ github.ref }}" =~ ^refs/tags/* ]]; then
            echo "A tag is pushed"
            [ "$game_version" == "$GITHUB_REF_NAME" ] && echo "The version file is correct" || exit 2
          fi

  build:
    needs: pre_check
    runs-on: ubuntu-20.04
    timeout-minutes: 30

    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: windows
            preset: Windows Desktop

          - platform: linux
            preset: Linux/X11

          # - platform: web
          #   preset: Web

          - platform: mac
            preset: macOS

    name: ${{ matrix.preset }} Export
    steps:
      - uses: actions/checkout@v4

      - name: Setup Versions Vars
        run: |
          echo "game_version=$(cat .version)" >> $GITHUB_ENV
          echo "godot_version=$(cat .godot_version)" >> $GITHUB_ENV
          ./bump_version.sh

      - name: Export Marble
        uses: ./.github/actions/export-game
        with:
          name: Marble
          platform: ${{ matrix.platform }}
          preset: ${{ matrix.preset }}
          version: ${{ env.game_version }}
          godot_version: ${{ env.godot_version }}

      - name: Upload artifact
        uses: ./.github/actions/upload-artifact
        with:
          name: Marble-${{ matrix.platform }}-v${{ env.game_version }}
          path: build/${{ matrix.platform }}

      # Installing rsync is needed in order to deploy to GitHub Pages. Without it, the build will fail.
      - name: Install rsync
        if: ${{ matrix.platform == 'web' }}
        run: |
          apt-get update && apt-get install -y rsync

      - name: Deploy to GitHub Pages
        if: ${{ matrix.platform == 'web' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages # The branch the action should deploy to.
          folder: build/web # The folder the action should deploy.
