name: Check and Lint

on:
  pull_request:
    paths:
      - 'scripts/**'
      - '**.gd'
  push:
    paths:
      - 'scripts/**'
      - '**.gd'

jobs:
  # Run the `gdlint` linting tool
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - run: pip3 install 'gdtoolkit==3.*'
      - run: gdlint scripts/
