
name: Flatpack Build

on:
  workflow_dispatch:

jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-44
      options: --privileged
    steps:
    - uses: actions/checkout@v4
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6.3
      with:
        bundle: marble.flatpak
        manifest-path: public/packaging/flatpak/org.mechanicalflower.Marble.yml
        cache-key: flatpak-builder-${{ github.sha }}
