name: Snapcraft Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v1

      - name: Load dotenv
        run: just bump-version

      - name: Build snap package
        uses: snapcore/action-build@v1
        with:
          path: public/packaging
        id: snapcraft

      # Push, on each commit of the main branch, to the edge channel
      - uses: snapcore/action-publish@v1
        if: github.ref == 'refs/heads/main'
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAP_STORE_LOGIN }}
        with:
          snap: ${{ steps.snapcraft.outputs.snap }}
          release: edge

      - name: Update the snapcraft to be stable
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          sed -i "s,grade:\ devel$,grade:\ stable\",g" ./public/packaging/snap/snapcraft.yaml
          sed -i "s,confinement:\ devmode$,confinement:\ strict,g" ./public/packaging/snap/snapcraft.yaml

      # Push, on each tag, to the stable channel
      - uses: snapcore/action-publish@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAP_STORE_LOGIN }}
        with:
          snap: ${{ steps.snapcraft.outputs.snap }}
          release: stable
