name: "Snapcraft build"

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build snap package
      uses: snapcore/action-build@v1
      id: snapcraft

    - name: Install built snap package
      run: |
        sudo snap install --dangerous ${{ steps.snapcraft.outputs.snap }}

    - name: Install dependencies for test launch
      run: |
        sudo apt install -y mesa-utils libgl1-mesa-dri libglx-mesa0

    - name: Test marble launch
      uses: GabrielBB/xvfb-action@v1.6
      with:
        run: /bin/bash public/packaging/snap/snap-xvfb-launch.sh
